# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cpu


### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.3178, 0.9234, 0.3814, 0.4251, 0.9368, 0.2947, 0.7804],
        [0.7677, 0.4631, 0.2865, 0.6212, 0.3145, 0.8146, 0.7386],
        [0.2232, 0.3214, 0.2367, 0.3166, 0.2922, 0.2704, 0.7468],
        [0.8870, 0.5552, 0.0938, 0.5095, 0.9626, 0.2827, 0.3254],
        [0.3908, 0.4476, 0.4199, 0.3371, 0.7864, 0.5288, 0.8885],
        [0.9610, 0.2101, 0.7170, 0.2856, 0.8692, 0.1570, 0.1400],
        [0.5553, 0.5911, 0.3511, 0.4376, 0.2752, 0.8848, 0.6604]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [18]:
# Create another random tensor
random_tensor_2 = torch.rand(1, 7)

# Perform matrix multiplication 
result = torch.matmul(random_tensor, random_tensor_2.T)
result

tensor([[1.9443],
        [1.9466],
        [1.2831],
        [1.4782],
        [1.7910],
        [1.3998],
        [1.8090]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
RANDOM_SEED = 0
# Create two random tensors
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_A = torch.rand(7, 7)
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
result = torch.matmul(random_tensor_A, random_tensor_B.T)
result

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
cuda = torch.device("cuda:0")
if torch.cuda.is_available():
  print(True)
else: 
  print('Not available')
  
torch.cuda.manual_seed(1234)
random_tensor_A = torch.rand(7, 7, device=cuda)
torch.cuda.manual_seed(1234)
random_tensor_B = torch.rand(1, 7, device=cuda)
random_tensor_A == random_tensor_B


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
device = "cuda"
random_tensor_A = torch.rand(3, 4, device=cuda)
random_tensor_B = torch.rand(3, 4, device=cuda)
torch.manual_seed(1234)
print(device)
print(random_tensor_A)
print(random_tensor_B)

AssertionError: Torch not compiled with CUDA enabled


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [27]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(random_tensor_A, random_tensor_B.T)
result

tensor([[0.3643, 0.4684, 0.5628],
        [0.4684, 0.7161, 0.5757],
        [0.5628, 0.5757, 1.4951]])

### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
print("Max value:", torch.max(result))
# Find min
print("Min value:", torch.min(result))

Max value: tensor(1.4951)
Min value: tensor(0.3643)


### 9. Find the maximum and minimum index values of the output of 7.

In [31]:
# Find arg max
print("Arg max:", torch.argmax(result))

# Find arg min
print("Arg min:", torch.argmin(result))

Arg max: tensor(8)
Arg min: tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [33]:
# Set seed
torch.manual_seed(42)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
random_tensor_2 = random_tensor.squeeze()
torch.manual_seed(7)
# Print out tensors and their shapes
print(random_tensor, random_tensor.shape)
print(random_tensor_2, random_tensor_2.shape)

tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936,
           0.9408, 0.1332]]]]) torch.Size([1, 1, 1, 10])
tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332]) torch.Size([10])
